# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "Entropy";
  version = "0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ ];
  meta = {
    platforms = self.ghc.meta.platforms;
  };
})
